// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go
//
// Generated by this command:
//
//	mockgen -source=broker.go -destination=mock_broker_test.go -package=broker_test -typed
//

// Package broker_test is a generated GoMock package.
package broker_test

import (
	context "context"
	reflect "reflect"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdapter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAdapterMockRecorder) Close(ctx any) *MockAdapterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdapter)(nil).Close), ctx)
	return &MockAdapterCloseCall{Call: call}
}

// MockAdapterCloseCall wrap *gomock.Call
type MockAdapterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterCloseCall) Return(arg0 error) *MockAdapterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterCloseCall) Do(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterCloseCall) DoAndReturn(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Connect mocks base method.
func (m *MockAdapter) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockAdapterMockRecorder) Connect(ctx any) *MockAdapterConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockAdapter)(nil).Connect), ctx)
	return &MockAdapterConnectCall{Call: call}
}

// MockAdapterConnectCall wrap *gomock.Call
type MockAdapterConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterConnectCall) Return(arg0 error) *MockAdapterConnectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterConnectCall) Do(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterConnectCall) DoAndReturn(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRecordProducer is a mock of RecordProducer interface.
type MockRecordProducer struct {
	ctrl     *gomock.Controller
	recorder *MockRecordProducerMockRecorder
	isgomock struct{}
}

// MockRecordProducerMockRecorder is the mock recorder for MockRecordProducer.
type MockRecordProducerMockRecorder struct {
	mock *MockRecordProducer
}

// NewMockRecordProducer creates a new mock instance.
func NewMockRecordProducer(ctrl *gomock.Controller) *MockRecordProducer {
	mock := &MockRecordProducer{ctrl: ctrl}
	mock.recorder = &MockRecordProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordProducer) EXPECT() *MockRecordProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRecordProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRecordProducerMockRecorder) Close() *MockRecordProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRecordProducer)(nil).Close))
	return &MockRecordProducerCloseCall{Call: call}
}

// MockRecordProducerCloseCall wrap *gomock.Call
type MockRecordProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerCloseCall) Return() *MockRecordProducerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerCloseCall) Do(f func()) *MockRecordProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerCloseCall) DoAndReturn(f func()) *MockRecordProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Flush mocks base method.
func (m *MockRecordProducer) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockRecordProducerMockRecorder) Flush(ctx any) *MockRecordProducerFlushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockRecordProducer)(nil).Flush), ctx)
	return &MockRecordProducerFlushCall{Call: call}
}

// MockRecordProducerFlushCall wrap *gomock.Call
type MockRecordProducerFlushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerFlushCall) Return(arg0 error) *MockRecordProducerFlushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerFlushCall) Do(f func(context.Context) error) *MockRecordProducerFlushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerFlushCall) DoAndReturn(f func(context.Context) error) *MockRecordProducerFlushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockRecordProducer) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRecordProducerMockRecorder) Ping(ctx any) *MockRecordProducerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRecordProducer)(nil).Ping), ctx)
	return &MockRecordProducerPingCall{Call: call}
}

// MockRecordProducerPingCall wrap *gomock.Call
type MockRecordProducerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerPingCall) Return(arg0 error) *MockRecordProducerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerPingCall) Do(f func(context.Context) error) *MockRecordProducerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerPingCall) DoAndReturn(f func(context.Context) error) *MockRecordProducerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Produce mocks base method.
func (m *MockRecordProducer) Produce(ctx context.Context, r *kgo.Record, promise func(*kgo.Record, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Produce", ctx, r, promise)
}

// Produce indicates an expected call of Produce.
func (mr *MockRecordProducerMockRecorder) Produce(ctx, r, promise any) *MockRecordProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockRecordProducer)(nil).Produce), ctx, r, promise)
	return &MockRecordProducerProduceCall{Call: call}
}

// MockRecordProducerProduceCall wrap *gomock.Call
type MockRecordProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerProduceCall) Return() *MockRecordProducerProduceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerProduceCall) Do(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockRecordProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerProduceCall) DoAndReturn(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockRecordProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPublishObserver is a mock of PublishObserver interface.
type MockPublishObserver struct {
	ctrl     *gomock.Controller
	recorder *MockPublishObserverMockRecorder
	isgomock struct{}
}

// MockPublishObserverMockRecorder is the mock recorder for MockPublishObserver.
type MockPublishObserverMockRecorder struct {
	mock *MockPublishObserver
}

// NewMockPublishObserver creates a new mock instance.
func NewMockPublishObserver(ctrl *gomock.Controller) *MockPublishObserver {
	mock := &MockPublishObserver{ctrl: ctrl}
	mock.recorder = &MockPublishObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublishObserver) EXPECT() *MockPublishObserverMockRecorder {
	return m.recorder
}

// PublishFailed mocks base method.
func (m *MockPublishObserver) PublishFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishFailed")
}

// PublishFailed indicates an expected call of PublishFailed.
func (mr *MockPublishObserverMockRecorder) PublishFailed() *MockPublishObserverPublishFailedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFailed", reflect.TypeOf((*MockPublishObserver)(nil).PublishFailed))
	return &MockPublishObserverPublishFailedCall{Call: call}
}

// MockPublishObserverPublishFailedCall wrap *gomock.Call
type MockPublishObserverPublishFailedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublishObserverPublishFailedCall) Return() *MockPublishObserverPublishFailedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublishObserverPublishFailedCall) Do(f func()) *MockPublishObserverPublishFailedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublishObserverPublishFailedCall) DoAndReturn(f func()) *MockPublishObserverPublishFailedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Published mocks base method.
func (m *MockPublishObserver) Published() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Published")
}

// Published indicates an expected call of Published.
func (mr *MockPublishObserverMockRecorder) Published() *MockPublishObserverPublishedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Published", reflect.TypeOf((*MockPublishObserver)(nil).Published))
	return &MockPublishObserverPublishedCall{Call: call}
}

// MockPublishObserverPublishedCall wrap *gomock.Call
type MockPublishObserverPublishedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublishObserverPublishedCall) Return() *MockPublishObserverPublishedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublishObserverPublishedCall) Do(f func()) *MockPublishObserverPublishedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublishObserverPublishedCall) DoAndReturn(f func()) *MockPublishObserverPublishedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
