// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go
//
// Generated by this command:
//
//	mockgen -source=broker.go -destination=mock_broker_test.go -package=broker -typed
//

// Package broker is a generated GoMock package.
package broker

import (
	events "wikirecent/internal/events"
	context "context"
	reflect "reflect"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdapter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAdapterMockRecorder) Close(ctx any) *MockAdapterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdapter)(nil).Close), ctx)
	return &MockAdapterCloseCall{Call: call}
}

// MockAdapterCloseCall wrap *gomock.Call
type MockAdapterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterCloseCall) Return(arg0 error) *MockAdapterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterCloseCall) Do(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterCloseCall) DoAndReturn(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Connect mocks base method.
func (m *MockAdapter) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockAdapterMockRecorder) Connect(ctx any) *MockAdapterConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockAdapter)(nil).Connect), ctx)
	return &MockAdapterConnectCall{Call: call}
}

// MockAdapterConnectCall wrap *gomock.Call
type MockAdapterConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterConnectCall) Return(arg0 error) *MockAdapterConnectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterConnectCall) Do(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterConnectCall) DoAndReturn(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mockrecorder is a mock of recorder interface.
type Mockrecorder struct {
	ctrl     *gomock.Controller
	recorder *MockrecorderMockRecorder
	isgomock struct{}
}

// MockrecorderMockRecorder is the mock recorder for Mockrecorder.
type MockrecorderMockRecorder struct {
	mock *Mockrecorder
}

// NewMockrecorder creates a new mock instance.
func NewMockrecorder(ctrl *gomock.Controller) *Mockrecorder {
	mock := &Mockrecorder{ctrl: ctrl}
	mock.recorder = &MockrecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrecorder) EXPECT() *MockrecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *Mockrecorder) Record(event events.WikiEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", event)
}

// Record indicates an expected call of Record.
func (mr *MockrecorderMockRecorder) Record(event any) *MockrecorderRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*Mockrecorder)(nil).Record), event)
	return &MockrecorderRecordCall{Call: call}
}

// MockrecorderRecordCall wrap *gomock.Call
type MockrecorderRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecorderRecordCall) Return() *MockrecorderRecordCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecorderRecordCall) Do(f func(events.WikiEvent)) *MockrecorderRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecorderRecordCall) DoAndReturn(f func(events.WikiEvent)) *MockrecorderRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockrecordProducer is a mock of recordProducer interface.
type MockrecordProducer struct {
	ctrl     *gomock.Controller
	recorder *MockrecordProducerMockRecorder
	isgomock struct{}
}

// MockrecordProducerMockRecorder is the mock recorder for MockrecordProducer.
type MockrecordProducerMockRecorder struct {
	mock *MockrecordProducer
}

// NewMockrecordProducer creates a new mock instance.
func NewMockrecordProducer(ctrl *gomock.Controller) *MockrecordProducer {
	mock := &MockrecordProducer{ctrl: ctrl}
	mock.recorder = &MockrecordProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecordProducer) EXPECT() *MockrecordProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockrecordProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockrecordProducerMockRecorder) Close() *MockrecordProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockrecordProducer)(nil).Close))
	return &MockrecordProducerCloseCall{Call: call}
}

// MockrecordProducerCloseCall wrap *gomock.Call
type MockrecordProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerCloseCall) Return() *MockrecordProducerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerCloseCall) Do(f func()) *MockrecordProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerCloseCall) DoAndReturn(f func()) *MockrecordProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Flush mocks base method.
func (m *MockrecordProducer) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockrecordProducerMockRecorder) Flush(ctx any) *MockrecordProducerFlushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockrecordProducer)(nil).Flush), ctx)
	return &MockrecordProducerFlushCall{Call: call}
}

// MockrecordProducerFlushCall wrap *gomock.Call
type MockrecordProducerFlushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerFlushCall) Return(arg0 error) *MockrecordProducerFlushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerFlushCall) Do(f func(context.Context) error) *MockrecordProducerFlushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerFlushCall) DoAndReturn(f func(context.Context) error) *MockrecordProducerFlushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockrecordProducer) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockrecordProducerMockRecorder) Ping(ctx any) *MockrecordProducerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockrecordProducer)(nil).Ping), ctx)
	return &MockrecordProducerPingCall{Call: call}
}

// MockrecordProducerPingCall wrap *gomock.Call
type MockrecordProducerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerPingCall) Return(arg0 error) *MockrecordProducerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerPingCall) Do(f func(context.Context) error) *MockrecordProducerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerPingCall) DoAndReturn(f func(context.Context) error) *MockrecordProducerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Produce mocks base method.
func (m *MockrecordProducer) Produce(ctx context.Context, r *kgo.Record, promise func(*kgo.Record, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Produce", ctx, r, promise)
}

// Produce indicates an expected call of Produce.
func (mr *MockrecordProducerMockRecorder) Produce(ctx, r, promise any) *MockrecordProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockrecordProducer)(nil).Produce), ctx, r, promise)
	return &MockrecordProducerProduceCall{Call: call}
}

// MockrecordProducerProduceCall wrap *gomock.Call
type MockrecordProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerProduceCall) Return() *MockrecordProducerProduceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerProduceCall) Do(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockrecordProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerProduceCall) DoAndReturn(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockrecordProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockrecordPoller is a mock of recordPoller interface.
type MockrecordPoller struct {
	ctrl     *gomock.Controller
	recorder *MockrecordPollerMockRecorder
	isgomock struct{}
}

// MockrecordPollerMockRecorder is the mock recorder for MockrecordPoller.
type MockrecordPollerMockRecorder struct {
	mock *MockrecordPoller
}

// NewMockrecordPoller creates a new mock instance.
func NewMockrecordPoller(ctrl *gomock.Controller) *MockrecordPoller {
	mock := &MockrecordPoller{ctrl: ctrl}
	mock.recorder = &MockrecordPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecordPoller) EXPECT() *MockrecordPollerMockRecorder {
	return m.recorder
}

// AllowRebalance mocks base method.
func (m *MockrecordPoller) AllowRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllowRebalance")
}

// AllowRebalance indicates an expected call of AllowRebalance.
func (mr *MockrecordPollerMockRecorder) AllowRebalance() *MockrecordPollerAllowRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRebalance", reflect.TypeOf((*MockrecordPoller)(nil).AllowRebalance))
	return &MockrecordPollerAllowRebalanceCall{Call: call}
}

// MockrecordPollerAllowRebalanceCall wrap *gomock.Call
type MockrecordPollerAllowRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordPollerAllowRebalanceCall) Return() *MockrecordPollerAllowRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordPollerAllowRebalanceCall) Do(f func()) *MockrecordPollerAllowRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordPollerAllowRebalanceCall) DoAndReturn(f func()) *MockrecordPollerAllowRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseAllowingRebalance mocks base method.
func (m *MockrecordPoller) CloseAllowingRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAllowingRebalance")
}

// CloseAllowingRebalance indicates an expected call of CloseAllowingRebalance.
func (mr *MockrecordPollerMockRecorder) CloseAllowingRebalance() *MockrecordPollerCloseAllowingRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAllowingRebalance", reflect.TypeOf((*MockrecordPoller)(nil).CloseAllowingRebalance))
	return &MockrecordPollerCloseAllowingRebalanceCall{Call: call}
}

// MockrecordPollerCloseAllowingRebalanceCall wrap *gomock.Call
type MockrecordPollerCloseAllowingRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordPollerCloseAllowingRebalanceCall) Return() *MockrecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordPollerCloseAllowingRebalanceCall) Do(f func()) *MockrecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordPollerCloseAllowingRebalanceCall) DoAndReturn(f func()) *MockrecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitRecords mocks base method.
func (m *MockrecordPoller) CommitRecords(ctx context.Context, rs ...*kgo.Record) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range rs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitRecords", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitRecords indicates an expected call of CommitRecords.
func (mr *MockrecordPollerMockRecorder) CommitRecords(ctx any, rs ...any) *MockrecordPollerCommitRecordsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, rs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitRecords", reflect.TypeOf((*MockrecordPoller)(nil).CommitRecords), varargs...)
	return &MockrecordPollerCommitRecordsCall{Call: call}
}

// MockrecordPollerCommitRecordsCall wrap *gomock.Call
type MockrecordPollerCommitRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordPollerCommitRecordsCall) Return(arg0 error) *MockrecordPollerCommitRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordPollerCommitRecordsCall) Do(f func(context.Context, ...*kgo.Record) error) *MockrecordPollerCommitRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordPollerCommitRecordsCall) DoAndReturn(f func(context.Context, ...*kgo.Record) error) *MockrecordPollerCommitRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockrecordPoller) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockrecordPollerMockRecorder) Ping(ctx any) *MockrecordPollerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockrecordPoller)(nil).Ping), ctx)
	return &MockrecordPollerPingCall{Call: call}
}

// MockrecordPollerPingCall wrap *gomock.Call
type MockrecordPollerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordPollerPingCall) Return(arg0 error) *MockrecordPollerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordPollerPingCall) Do(f func(context.Context) error) *MockrecordPollerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordPollerPingCall) DoAndReturn(f func(context.Context) error) *MockrecordPollerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PollRecords mocks base method.
func (m *MockrecordPoller) PollRecords(ctx context.Context, maxRecords int) kgo.Fetches {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollRecords", ctx, maxRecords)
	ret0, _ := ret[0].(kgo.Fetches)
	return ret0
}

// PollRecords indicates an expected call of PollRecords.
func (mr *MockrecordPollerMockRecorder) PollRecords(ctx, maxRecords any) *MockrecordPollerPollRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollRecords", reflect.TypeOf((*MockrecordPoller)(nil).PollRecords), ctx, maxRecords)
	return &MockrecordPollerPollRecordsCall{Call: call}
}

// MockrecordPollerPollRecordsCall wrap *gomock.Call
type MockrecordPollerPollRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordPollerPollRecordsCall) Return(arg0 kgo.Fetches) *MockrecordPollerPollRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordPollerPollRecordsCall) Do(f func(context.Context, int) kgo.Fetches) *MockrecordPollerPollRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordPollerPollRecordsCall) DoAndReturn(f func(context.Context, int) kgo.Fetches) *MockrecordPollerPollRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
