// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go
//
// Generated by this command:
//
//	mockgen -source=broker.go -destination=mock_broker_test.go -package=broker_test -typed
//

// Package broker_test is a generated GoMock package.
package broker_test

import (
	context "context"
	reflect "reflect"
	events "wikirecent/internal/events"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdapter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAdapterMockRecorder) Close(ctx any) *MockAdapterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdapter)(nil).Close), ctx)
	return &MockAdapterCloseCall{Call: call}
}

// MockAdapterCloseCall wrap *gomock.Call
type MockAdapterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterCloseCall) Return(arg0 error) *MockAdapterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterCloseCall) Do(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterCloseCall) DoAndReturn(f func(context.Context) error) *MockAdapterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Connect mocks base method.
func (m *MockAdapter) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockAdapterMockRecorder) Connect(ctx any) *MockAdapterConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockAdapter)(nil).Connect), ctx)
	return &MockAdapterConnectCall{Call: call}
}

// MockAdapterConnectCall wrap *gomock.Call
type MockAdapterConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterConnectCall) Return(arg0 error) *MockAdapterConnectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterConnectCall) Do(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterConnectCall) DoAndReturn(f func(context.Context) error) *MockAdapterConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockRecorder) Record(event events.WikiEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", event)
}

// Record indicates an expected call of Record.
func (mr *MockRecorderMockRecorder) Record(event any) *MockRecorderRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRecorder)(nil).Record), event)
	return &MockRecorderRecordCall{Call: call}
}

// MockRecorderRecordCall wrap *gomock.Call
type MockRecorderRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecorderRecordCall) Return() *MockRecorderRecordCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecorderRecordCall) Do(f func(events.WikiEvent)) *MockRecorderRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecorderRecordCall) DoAndReturn(f func(events.WikiEvent)) *MockRecorderRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRecordProducer is a mock of RecordProducer interface.
type MockRecordProducer struct {
	ctrl     *gomock.Controller
	recorder *MockRecordProducerMockRecorder
	isgomock struct{}
}

// MockRecordProducerMockRecorder is the mock recorder for MockRecordProducer.
type MockRecordProducerMockRecorder struct {
	mock *MockRecordProducer
}

// NewMockRecordProducer creates a new mock instance.
func NewMockRecordProducer(ctrl *gomock.Controller) *MockRecordProducer {
	mock := &MockRecordProducer{ctrl: ctrl}
	mock.recorder = &MockRecordProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordProducer) EXPECT() *MockRecordProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRecordProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRecordProducerMockRecorder) Close() *MockRecordProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRecordProducer)(nil).Close))
	return &MockRecordProducerCloseCall{Call: call}
}

// MockRecordProducerCloseCall wrap *gomock.Call
type MockRecordProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerCloseCall) Return() *MockRecordProducerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerCloseCall) Do(f func()) *MockRecordProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerCloseCall) DoAndReturn(f func()) *MockRecordProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Flush mocks base method.
func (m *MockRecordProducer) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockRecordProducerMockRecorder) Flush(ctx any) *MockRecordProducerFlushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockRecordProducer)(nil).Flush), ctx)
	return &MockRecordProducerFlushCall{Call: call}
}

// MockRecordProducerFlushCall wrap *gomock.Call
type MockRecordProducerFlushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerFlushCall) Return(arg0 error) *MockRecordProducerFlushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerFlushCall) Do(f func(context.Context) error) *MockRecordProducerFlushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerFlushCall) DoAndReturn(f func(context.Context) error) *MockRecordProducerFlushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockRecordProducer) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRecordProducerMockRecorder) Ping(ctx any) *MockRecordProducerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRecordProducer)(nil).Ping), ctx)
	return &MockRecordProducerPingCall{Call: call}
}

// MockRecordProducerPingCall wrap *gomock.Call
type MockRecordProducerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerPingCall) Return(arg0 error) *MockRecordProducerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerPingCall) Do(f func(context.Context) error) *MockRecordProducerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerPingCall) DoAndReturn(f func(context.Context) error) *MockRecordProducerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Produce mocks base method.
func (m *MockRecordProducer) Produce(ctx context.Context, r *kgo.Record, promise func(*kgo.Record, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Produce", ctx, r, promise)
}

// Produce indicates an expected call of Produce.
func (mr *MockRecordProducerMockRecorder) Produce(ctx, r, promise any) *MockRecordProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockRecordProducer)(nil).Produce), ctx, r, promise)
	return &MockRecordProducerProduceCall{Call: call}
}

// MockRecordProducerProduceCall wrap *gomock.Call
type MockRecordProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordProducerProduceCall) Return() *MockRecordProducerProduceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordProducerProduceCall) Do(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockRecordProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordProducerProduceCall) DoAndReturn(f func(context.Context, *kgo.Record, func(*kgo.Record, error))) *MockRecordProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRecordPoller is a mock of RecordPoller interface.
type MockRecordPoller struct {
	ctrl     *gomock.Controller
	recorder *MockRecordPollerMockRecorder
	isgomock struct{}
}

// MockRecordPollerMockRecorder is the mock recorder for MockRecordPoller.
type MockRecordPollerMockRecorder struct {
	mock *MockRecordPoller
}

// NewMockRecordPoller creates a new mock instance.
func NewMockRecordPoller(ctrl *gomock.Controller) *MockRecordPoller {
	mock := &MockRecordPoller{ctrl: ctrl}
	mock.recorder = &MockRecordPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordPoller) EXPECT() *MockRecordPollerMockRecorder {
	return m.recorder
}

// AllowRebalance mocks base method.
func (m *MockRecordPoller) AllowRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllowRebalance")
}

// AllowRebalance indicates an expected call of AllowRebalance.
func (mr *MockRecordPollerMockRecorder) AllowRebalance() *MockRecordPollerAllowRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRebalance", reflect.TypeOf((*MockRecordPoller)(nil).AllowRebalance))
	return &MockRecordPollerAllowRebalanceCall{Call: call}
}

// MockRecordPollerAllowRebalanceCall wrap *gomock.Call
type MockRecordPollerAllowRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordPollerAllowRebalanceCall) Return() *MockRecordPollerAllowRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordPollerAllowRebalanceCall) Do(f func()) *MockRecordPollerAllowRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordPollerAllowRebalanceCall) DoAndReturn(f func()) *MockRecordPollerAllowRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseAllowingRebalance mocks base method.
func (m *MockRecordPoller) CloseAllowingRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAllowingRebalance")
}

// CloseAllowingRebalance indicates an expected call of CloseAllowingRebalance.
func (mr *MockRecordPollerMockRecorder) CloseAllowingRebalance() *MockRecordPollerCloseAllowingRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAllowingRebalance", reflect.TypeOf((*MockRecordPoller)(nil).CloseAllowingRebalance))
	return &MockRecordPollerCloseAllowingRebalanceCall{Call: call}
}

// MockRecordPollerCloseAllowingRebalanceCall wrap *gomock.Call
type MockRecordPollerCloseAllowingRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordPollerCloseAllowingRebalanceCall) Return() *MockRecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordPollerCloseAllowingRebalanceCall) Do(f func()) *MockRecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordPollerCloseAllowingRebalanceCall) DoAndReturn(f func()) *MockRecordPollerCloseAllowingRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitRecords mocks base method.
func (m *MockRecordPoller) CommitRecords(ctx context.Context, rs ...*kgo.Record) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range rs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitRecords", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitRecords indicates an expected call of CommitRecords.
func (mr *MockRecordPollerMockRecorder) CommitRecords(ctx any, rs ...any) *MockRecordPollerCommitRecordsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, rs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitRecords", reflect.TypeOf((*MockRecordPoller)(nil).CommitRecords), varargs...)
	return &MockRecordPollerCommitRecordsCall{Call: call}
}

// MockRecordPollerCommitRecordsCall wrap *gomock.Call
type MockRecordPollerCommitRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordPollerCommitRecordsCall) Return(arg0 error) *MockRecordPollerCommitRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordPollerCommitRecordsCall) Do(f func(context.Context, ...*kgo.Record) error) *MockRecordPollerCommitRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordPollerCommitRecordsCall) DoAndReturn(f func(context.Context, ...*kgo.Record) error) *MockRecordPollerCommitRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockRecordPoller) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRecordPollerMockRecorder) Ping(ctx any) *MockRecordPollerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRecordPoller)(nil).Ping), ctx)
	return &MockRecordPollerPingCall{Call: call}
}

// MockRecordPollerPingCall wrap *gomock.Call
type MockRecordPollerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordPollerPingCall) Return(arg0 error) *MockRecordPollerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordPollerPingCall) Do(f func(context.Context) error) *MockRecordPollerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordPollerPingCall) DoAndReturn(f func(context.Context) error) *MockRecordPollerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PollRecords mocks base method.
func (m *MockRecordPoller) PollRecords(ctx context.Context, maxRecords int) kgo.Fetches {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollRecords", ctx, maxRecords)
	ret0, _ := ret[0].(kgo.Fetches)
	return ret0
}

// PollRecords indicates an expected call of PollRecords.
func (mr *MockRecordPollerMockRecorder) PollRecords(ctx, maxRecords any) *MockRecordPollerPollRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollRecords", reflect.TypeOf((*MockRecordPoller)(nil).PollRecords), ctx, maxRecords)
	return &MockRecordPollerPollRecordsCall{Call: call}
}

// MockRecordPollerPollRecordsCall wrap *gomock.Call
type MockRecordPollerPollRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordPollerPollRecordsCall) Return(arg0 kgo.Fetches) *MockRecordPollerPollRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordPollerPollRecordsCall) Do(f func(context.Context, int) kgo.Fetches) *MockRecordPollerPollRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordPollerPollRecordsCall) DoAndReturn(f func(context.Context, int) kgo.Fetches) *MockRecordPollerPollRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
