// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wikirecent/v1/wiki_event.proto

package wikiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WikiEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Bot              bool                   `protobuf:"varint,2,opt,name=bot,proto3" json:"bot,omitempty"`
	ServerUrl        string                 `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Namespace        int32                  `protobuf:"varint,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Minor            bool                   `protobuf:"varint,8,opt,name=minor,proto3" json:"minor,omitempty"`
	Patrolled        *bool                  `protobuf:"varint,9,opt,name=patrolled,proto3,oneof" json:"patrolled,omitempty"`
	Id               *int64                 `protobuf:"varint,10,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Wiki             string                 `protobuf:"bytes,11,opt,name=wiki,proto3" json:"wiki,omitempty"`
	Comment          string                 `protobuf:"bytes,12,opt,name=comment,proto3" json:"comment,omitempty"`
	Meta             *Meta                  `protobuf:"bytes,13,opt,name=meta,proto3" json:"meta,omitempty"`
	Length           *PageLength            `protobuf:"bytes,14,opt,name=length,proto3" json:"length,omitempty"`
	Revision         *RevisionIds           `protobuf:"bytes,15,opt,name=revision,proto3" json:"revision,omitempty"`
	TitleUrl         string                 `protobuf:"bytes,16,opt,name=title_url,json=titleUrl,proto3" json:"title_url,omitempty"`
	Parsedcomment    string                 `protobuf:"bytes,17,opt,name=parsedcomment,proto3" json:"parsedcomment,omitempty"`
	ServerName       string                 `protobuf:"bytes,18,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerScriptPath string                 `protobuf:"bytes,19,opt,name=server_script_path,json=serverScriptPath,proto3" json:"server_script_path,omitempty"`
	NotifyUrl        string                 `protobuf:"bytes,20,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Schema           string                 `protobuf:"bytes,21,opt,name=schema,proto3" json:"schema,omitempty"`
	Log              *Log                   `protobuf:"bytes,22,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WikiEvent) Reset() {
	*x = WikiEvent{}
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WikiEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WikiEvent) ProtoMessage() {}

func (x *WikiEvent) ProtoReflect() protoreflect.Message {
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WikiEvent.ProtoReflect.Descriptor instead.
func (*WikiEvent) Descriptor() ([]byte, []int) {
	return file_wikirecent_v1_wiki_event_proto_rawDescGZIP(), []int{0}
}

func (x *WikiEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *WikiEvent) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *WikiEvent) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *WikiEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WikiEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WikiEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WikiEvent) GetNamespace() int32 {
	if x != nil {
		return x.Namespace
	}
	return 0
}

func (x *WikiEvent) GetMinor() bool {
	if x != nil {
		return x.Minor
	}
	return false
}

func (x *WikiEvent) GetPatrolled() bool {
	if x != nil && x.Patrolled != nil {
		return *x.Patrolled
	}
	return false
}

func (x *WikiEvent) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *WikiEvent) GetWiki() string {
	if x != nil {
		return x.Wiki
	}
	return ""
}

func (x *WikiEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *WikiEvent) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *WikiEvent) GetLength() *PageLength {
	if x != nil {
		return x.Length
	}
	return nil
}

func (x *WikiEvent) GetRevision() *RevisionIds {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *WikiEvent) GetTitleUrl() string {
	if x != nil {
		return x.TitleUrl
	}
	return ""
}

func (x *WikiEvent) GetParsedcomment() string {
	if x != nil {
		return x.Parsedcomment
	}
	return ""
}

func (x *WikiEvent) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *WikiEvent) GetServerScriptPath() string {
	if x != nil {
		return x.ServerScriptPath
	}
	return ""
}

func (x *WikiEvent) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *WikiEvent) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *WikiEvent) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Dt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dt,proto3" json:"dt,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream        string                 `protobuf:"bytes,6,opt,name=stream,proto3" json:"stream,omitempty"`
	Topic         string                 `protobuf:"bytes,7,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,8,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_wikirecent_v1_wiki_event_proto_rawDescGZIP(), []int{1}
}

func (x *Meta) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Meta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Meta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Meta) GetDt() *timestamppb.Timestamp {
	if x != nil {
		return x.Dt
	}
	return nil
}

func (x *Meta) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Meta) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Meta) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Meta) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Meta) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PageLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldBytes      *int64                 `protobuf:"varint,1,opt,name=old_bytes,json=oldBytes,proto3,oneof" json:"old_bytes,omitempty"`
	NewBytes      *int64                 `protobuf:"varint,2,opt,name=new_bytes,json=newBytes,proto3,oneof" json:"new_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageLength) Reset() {
	*x = PageLength{}
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLength) ProtoMessage() {}

func (x *PageLength) ProtoReflect() protoreflect.Message {
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLength.ProtoReflect.Descriptor instead.
func (*PageLength) Descriptor() ([]byte, []int) {
	return file_wikirecent_v1_wiki_event_proto_rawDescGZIP(), []int{2}
}

func (x *PageLength) GetOldBytes() int64 {
	if x != nil && x.OldBytes != nil {
		return *x.OldBytes
	}
	return 0
}

func (x *PageLength) GetNewBytes() int64 {
	if x != nil && x.NewBytes != nil {
		return *x.NewBytes
	}
	return 0
}

type RevisionIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldId         *int64                 `protobuf:"varint,1,opt,name=old_id,json=oldId,proto3,oneof" json:"old_id,omitempty"`
	NewId         *int64                 `protobuf:"varint,2,opt,name=new_id,json=newId,proto3,oneof" json:"new_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionIds) Reset() {
	*x = RevisionIds{}
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionIds) ProtoMessage() {}

func (x *RevisionIds) ProtoReflect() protoreflect.Message {
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionIds.ProtoReflect.Descriptor instead.
func (*RevisionIds) Descriptor() ([]byte, []int) {
	return file_wikirecent_v1_wiki_event_proto_rawDescGZIP(), []int{3}
}

func (x *RevisionIds) GetOldId() int64 {
	if x != nil && x.OldId != nil {
		return *x.OldId
	}
	return 0
}

func (x *RevisionIds) GetNewId() int64 {
	if x != nil && x.NewId != nil {
		return *x.NewId
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActionComment string                 `protobuf:"bytes,4,opt,name=action_comment,json=actionComment,proto3" json:"action_comment,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,5,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_wikirecent_v1_wiki_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_wikirecent_v1_wiki_event_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Log) GetActionComment() string {
	if x != nil {
		return x.ActionComment
	}
	return ""
}

func (x *Log) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

var File_wikirecent_v1_wiki_event_proto protoreflect.FileDescriptor

const file_wikirecent_v1_wiki_event_proto_rawDesc = "" +
	"\n" +
	"\x1ewikirecent/v1/wiki_event.proto\x12\rwikirecent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x05\n" +
	"\tWikiEvent\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03bot\x18\x02 \x01(\bR\x03bot\x12\x1d\n" +
	"\n" +
	"server_url\x18\x03 \x01(\tR\tserverUrl\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\x05R\tnamespace\x12\x14\n" +
	"\x05minor\x18\b \x01(\bR\x05minor\x12!\n" +
	"\tpatrolled\x18\t \x01(\bH\x00R\tpatrolled\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\n" +
	" \x01(\x03H\x01R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04wiki\x18\v \x01(\tR\x04wiki\x12\x18\n" +
	"\acomment\x18\f \x01(\tR\acomment\x12'\n" +
	"\x04meta\x18\r \x01(\v2\x13.wikirecent.v1.MetaR\x04meta\x121\n" +
	"\x06length\x18\x0e \x01(\v2\x19.wikirecent.v1.PageLengthR\x06length\x126\n" +
	"\brevision\x18\x0f \x01(\v2\x1a.wikirecent.v1.RevisionIdsR\brevision\x12\x1b\n" +
	"\ttitle_url\x18\x10 \x01(\tR\btitleUrl\x12$\n" +
	"\rparsedcomment\x18\x11 \x01(\tR\rparsedcomment\x12\x1f\n" +
	"\vserver_name\x18\x12 \x01(\tR\n" +
	"serverName\x12,\n" +
	"\x12server_script_path\x18\x13 \x01(\tR\x10serverScriptPath\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x14 \x01(\tR\tnotifyUrl\x12\x16\n" +
	"\x06schema\x18\x15 \x01(\tR\x06schema\x12$\n" +
	"\x03log\x18\x16 \x01(\v2\x12.wikirecent.v1.LogR\x03logB\f\n" +
	"\n" +
	"_patrolledB\x05\n" +
	"\x03_id\"\xef\x01\n" +
	"\x04Meta\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12*\n" +
	"\x02dt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02dt\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\tR\x06stream\x12\x14\n" +
	"\x05topic\x18\a \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\b \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\t \x01(\x03R\x06offset\"l\n" +
	"\n" +
	"PageLength\x12 \n" +
	"\told_bytes\x18\x01 \x01(\x03H\x00R\boldBytes\x88\x01\x01\x12 \n" +
	"\tnew_bytes\x18\x02 \x01(\x03H\x01R\bnewBytes\x88\x01\x01B\f\n" +
	"\n" +
	"_old_bytesB\f\n" +
	"\n" +
	"_new_bytes\"[\n" +
	"\vRevisionIds\x12\x1a\n" +
	"\x06old_id\x18\x01 \x01(\x03H\x00R\x05oldId\x88\x01\x01\x12\x1a\n" +
	"\x06new_id\x18\x02 \x01(\x03H\x01R\x05newId\x88\x01\x01B\t\n" +
	"\a_old_idB\t\n" +
	"\a_new_id\"\x95\x01\n" +
	"\x03Log\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12%\n" +
	"\x0eaction_comment\x18\x04 \x01(\tR\ractionComment\x12\x1f\n" +
	"\vparams_json\x18\x05 \x01(\tR\n" +
	"paramsJsonB\x05\n" +
	"\x03_idB3Z1wikirecent/internal/genproto/wikirecent/v1;wikiv1b\x06proto3"

var (
	file_wikirecent_v1_wiki_event_proto_rawDescOnce sync.Once
	file_wikirecent_v1_wiki_event_proto_rawDescData []byte
)

func file_wikirecent_v1_wiki_event_proto_rawDescGZIP() []byte {
	file_wikirecent_v1_wiki_event_proto_rawDescOnce.Do(func() {
		file_wikirecent_v1_wiki_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wikirecent_v1_wiki_event_proto_rawDesc), len(file_wikirecent_v1_wiki_event_proto_rawDesc)))
	})
	return file_wikirecent_v1_wiki_event_proto_rawDescData
}

var file_wikirecent_v1_wiki_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wikirecent_v1_wiki_event_proto_goTypes = []any{
	(*WikiEvent)(nil),             // 0: wikirecent.v1.WikiEvent
	(*Meta)(nil),                  // 1: wikirecent.v1.Meta
	(*PageLength)(nil),            // 2: wikirecent.v1.PageLength
	(*RevisionIds)(nil),           // 3: wikirecent.v1.RevisionIds
	(*Log)(nil),                   // 4: wikirecent.v1.Log
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_wikirecent_v1_wiki_event_proto_depIdxs = []int32{
	5, // 0: wikirecent.v1.WikiEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: wikirecent.v1.WikiEvent.meta:type_name -> wikirecent.v1.Meta
	2, // 2: wikirecent.v1.WikiEvent.length:type_name -> wikirecent.v1.PageLength
	3, // 3: wikirecent.v1.WikiEvent.revision:type_name -> wikirecent.v1.RevisionIds
	4, // 4: wikirecent.v1.WikiEvent.log:type_name -> wikirecent.v1.Log
	5, // 5: wikirecent.v1.Meta.dt:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wikirecent_v1_wiki_event_proto_init() }
func file_wikirecent_v1_wiki_event_proto_init() {
	if File_wikirecent_v1_wiki_event_proto != nil {
		return
	}
	file_wikirecent_v1_wiki_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_wikirecent_v1_wiki_event_proto_msgTypes[2].OneofWrappers = []any{}
	file_wikirecent_v1_wiki_event_proto_msgTypes[3].OneofWrappers = []any{}
	file_wikirecent_v1_wiki_event_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wikirecent_v1_wiki_event_proto_rawDesc), len(file_wikirecent_v1_wiki_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wikirecent_v1_wiki_event_proto_goTypes,
		DependencyIndexes: file_wikirecent_v1_wiki_event_proto_depIdxs,
		MessageInfos:      file_wikirecent_v1_wiki_event_proto_msgTypes,
	}.Build()
	File_wikirecent_v1_wiki_event_proto = out.File
	file_wikirecent_v1_wiki_event_proto_goTypes = nil
	file_wikirecent_v1_wiki_event_proto_depIdxs = nil
}
