// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mock_metrics_test.go -package=metrics_test -typed
//

// Package metrics_test is a generated GoMock package.
package metrics_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mocksink is a mock of sink interface.
type Mocksink struct {
	ctrl     *gomock.Controller
	recorder *MocksinkMockRecorder
	isgomock struct{}
}

// MocksinkMockRecorder is the mock recorder for Mocksink.
type MocksinkMockRecorder struct {
	mock *Mocksink
}

// NewMocksink creates a new mock instance.
func NewMocksink(ctrl *gomock.Controller) *Mocksink {
	mock := &Mocksink{ctrl: ctrl}
	mock.recorder = &MocksinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksink) EXPECT() *MocksinkMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *Mocksink) Publish(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MocksinkMockRecorder) Publish(ctx, payload any) *MocksinkPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*Mocksink)(nil).Publish), ctx, payload)
	return &MocksinkPublishCall{Call: call}
}

// MocksinkPublishCall wrap *gomock.Call
type MocksinkPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksinkPublishCall) Return(arg0 error) *MocksinkPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksinkPublishCall) Do(f func(context.Context, []byte) error) *MocksinkPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksinkPublishCall) DoAndReturn(f func(context.Context, []byte) error) *MocksinkPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
