global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: wikistream
    metrics_path: /metrics
    static_configs:
      - targets: ["producer:7002"]
        labels:
          application: producer
      - targets: ["rpcn-ingest:4195"]
        labels:
          application: consumer
