// Code generated by MockGen. DO NOT EDIT.
// Source: wikistream.go
//
// Generated by this command:
//
//	mockgen -source=wikistream.go -destination=mock_wikistream_test.go -package=wikistream -typed
//

// Package wikistream is a generated GoMock package.
package wikistream

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockdoer is a mock of doer interface.
type Mockdoer struct {
	ctrl     *gomock.Controller
	recorder *MockdoerMockRecorder
	isgomock struct{}
}

// MockdoerMockRecorder is the mock recorder for Mockdoer.
type MockdoerMockRecorder struct {
	mock *Mockdoer
}

// NewMockdoer creates a new mock instance.
func NewMockdoer(ctrl *gomock.Controller) *Mockdoer {
	mock := &Mockdoer{ctrl: ctrl}
	mock.recorder = &MockdoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdoer) EXPECT() *MockdoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *Mockdoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockdoerMockRecorder) Do(req any) *MockdoerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*Mockdoer)(nil).Do), req)
	return &MockdoerDoCall{Call: call}
}

// MockdoerDoCall wrap *gomock.Call
type MockdoerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockdoerDoCall) Return(arg0 *http.Response, arg1 error) *MockdoerDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockdoerDoCall) Do(f func(*http.Request) (*http.Response, error)) *MockdoerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockdoerDoCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockdoerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSink) Publish(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSinkMockRecorder) Publish(ctx, payload any) *MockSinkPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSink)(nil).Publish), ctx, payload)
	return &MockSinkPublishCall{Call: call}
}

// MockSinkPublishCall wrap *gomock.Call
type MockSinkPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSinkPublishCall) Return(arg0 error) *MockSinkPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSinkPublishCall) Do(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSinkPublishCall) DoAndReturn(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
