// Code generated by MockGen. DO NOT EDIT.
// Source: wikistream.go
//
// Generated by this command:
//
//	mockgen -source=wikistream.go -destination=mock_wikistream_test.go -package=wikistream_test -typed
//

// Package wikistream_test is a generated GoMock package.
package wikistream_test

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDoer is a mock of Doer interface.
type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *MockDoerMockRecorder
	isgomock struct{}
}

// MockDoerMockRecorder is the mock recorder for MockDoer.
type MockDoerMockRecorder struct {
	mock *MockDoer
}

// NewMockDoer creates a new mock instance.
func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &MockDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoer) EXPECT() *MockDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockDoerMockRecorder) Do(req any) *MockDoerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDoer)(nil).Do), req)
	return &MockDoerDoCall{Call: call}
}

// MockDoerDoCall wrap *gomock.Call
type MockDoerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDoerDoCall) Return(arg0 *http.Response, arg1 error) *MockDoerDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDoerDoCall) Do(f func(*http.Request) (*http.Response, error)) *MockDoerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDoerDoCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockDoerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSink) Publish(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSinkMockRecorder) Publish(ctx, payload any) *MockSinkPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSink)(nil).Publish), ctx, payload)
	return &MockSinkPublishCall{Call: call}
}

// MockSinkPublishCall wrap *gomock.Call
type MockSinkPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSinkPublishCall) Return(arg0 error) *MockSinkPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSinkPublishCall) Do(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSinkPublishCall) DoAndReturn(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
