// Code generated by MockGen. DO NOT EDIT.
// Source: sink.go
//
// Generated by this command:
//
//	mockgen -source=sink.go -destination=mock_sink_test.go -package=codec_test -typed
//

// Package codec_test is a generated GoMock package.
package codec_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSink) Publish(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSinkMockRecorder) Publish(ctx, payload any) *MockSinkPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSink)(nil).Publish), ctx, payload)
	return &MockSinkPublishCall{Call: call}
}

// MockSinkPublishCall wrap *gomock.Call
type MockSinkPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSinkPublishCall) Return(arg0 error) *MockSinkPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSinkPublishCall) Do(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSinkPublishCall) DoAndReturn(f func(context.Context, []byte) error) *MockSinkPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
