// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mock_api_test.go -package=httpapi_test -typed
//

// Package httpapi_test is a generated GoMock package.
package httpapi_test

import (
	context "context"
	reflect "reflect"
	statsmodels "wikirecent/internal/stats/statsmodels"

	gomock "go.uber.org/mock/gomock"
)

// Mocksnapshotter is a mock of snapshotter interface.
type Mocksnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MocksnapshotterMockRecorder
	isgomock struct{}
}

// MocksnapshotterMockRecorder is the mock recorder for Mocksnapshotter.
type MocksnapshotterMockRecorder struct {
	mock *Mocksnapshotter
}

// NewMocksnapshotter creates a new mock instance.
func NewMocksnapshotter(ctrl *gomock.Controller) *Mocksnapshotter {
	mock := &Mocksnapshotter{ctrl: ctrl}
	mock.recorder = &MocksnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksnapshotter) EXPECT() *MocksnapshotterMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *Mocksnapshotter) Snapshot(ctx context.Context) (statsmodels.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(statsmodels.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MocksnapshotterMockRecorder) Snapshot(ctx any) *MocksnapshotterSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*Mocksnapshotter)(nil).Snapshot), ctx)
	return &MocksnapshotterSnapshotCall{Call: call}
}

// MocksnapshotterSnapshotCall wrap *gomock.Call
type MocksnapshotterSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksnapshotterSnapshotCall) Return(arg0 statsmodels.Snapshot, arg1 error) *MocksnapshotterSnapshotCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksnapshotterSnapshotCall) Do(f func(context.Context) (statsmodels.Snapshot, error)) *MocksnapshotterSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksnapshotterSnapshotCall) DoAndReturn(f func(context.Context) (statsmodels.Snapshot, error)) *MocksnapshotterSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
