// Code generated by MockGen. DO NOT EDIT.
// Source: internal/consumer/consumer.go
//
// Generated by this command:
//
//	mockgen -source=internal/consumer/consumer.go -destination=mock_consumer_test.go -package=consumer -typed
//

// Package consumer is a generated GoMock package.
package consumer

import (
	models "ch-2/internal/consumer/models"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockrecorder is a mock of recorder interface.
type Mockrecorder struct {
	ctrl     *gomock.Controller
	recorder *MockrecorderMockRecorder
	isgomock struct{}
}

// MockrecorderMockRecorder is the mock recorder for Mockrecorder.
type MockrecorderMockRecorder struct {
	mock *Mockrecorder
}

// NewMockrecorder creates a new mock instance.
func NewMockrecorder(ctrl *gomock.Controller) *Mockrecorder {
	mock := &Mockrecorder{ctrl: ctrl}
	mock.recorder = &MockrecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrecorder) EXPECT() *MockrecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *Mockrecorder) Record(event models.WikiEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", event)
}

// Record indicates an expected call of Record.
func (mr *MockrecorderMockRecorder) Record(event any) *MockrecorderRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*Mockrecorder)(nil).Record), event)
	return &MockrecorderRecordCall{Call: call}
}

// MockrecorderRecordCall wrap *gomock.Call
type MockrecorderRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecorderRecordCall) Return() *MockrecorderRecordCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecorderRecordCall) Do(f func(models.WikiEvent)) *MockrecorderRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecorderRecordCall) DoAndReturn(f func(models.WikiEvent)) *MockrecorderRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mockdoer is a mock of doer interface.
type Mockdoer struct {
	ctrl     *gomock.Controller
	recorder *MockdoerMockRecorder
	isgomock struct{}
}

// MockdoerMockRecorder is the mock recorder for Mockdoer.
type MockdoerMockRecorder struct {
	mock *Mockdoer
}

// NewMockdoer creates a new mock instance.
func NewMockdoer(ctrl *gomock.Controller) *Mockdoer {
	mock := &Mockdoer{ctrl: ctrl}
	mock.recorder = &MockdoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdoer) EXPECT() *MockdoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *Mockdoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockdoerMockRecorder) Do(req any) *MockdoerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*Mockdoer)(nil).Do), req)
	return &MockdoerDoCall{Call: call}
}

// MockdoerDoCall wrap *gomock.Call
type MockdoerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockdoerDoCall) Return(arg0 *http.Response, arg1 error) *MockdoerDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockdoerDoCall) Do(f func(*http.Request) (*http.Response, error)) *MockdoerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockdoerDoCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockdoerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
